### ISSUE TITLE
Scaling of glyphs to UPM?

### ISSUE THREAD

**Issue by davelab6** [rosettatype/Eczar#9] opened 2015-01-28 01:10 UTC
The scaling of Eczar compared to other Devanagari fonts seems very small:

![screen shot 2015-01-27 at 8 08 31 pm](https://cloud.githubusercontent.com/assets/261579/5930647/46030db2-a660-11e4-82d4-d603e4415e19.png)

I believe that the UPM was changed to 2048 while the glyphs themselves were not rescaled; a UPM of 1000 is preferable for web fonts as it reduces the filesize. 

```
$ fontbakery-fix-vertical-metrics.py Eczar-*.ttf 
Parameter              Eczar-Bold.ttf    Eczar-Extrabold.ttf    Eczar-Medium.ttf    Eczar-Regular.ttf    Eczar-Semibold.ttf    
ymax                   1110              1143                   1046                1016                 1078                  
hhea.ascent            1288              1288                   1288                1288                 1288                  
OS/2.sTypoAscender     1188              1188                   1188                1188                 1188                  
OS/2.usWinAscent       1288              1288                   1288                1288                 1288                  
ymin                   -594              -634                   -513                -473                 -554                  
hhea.descent           -960              -960                   -960                -960                 -960                  
OS/2.sTypoDescender    -860              -860                   -860                -860                 -860                  
OS/2.usWinDescent      960               960                    960                 960                  960                   
hhea.lineGap           0                 0                      0                   0                    0                     
OS/2.sTypoLineGap      200               200                    200                 200                  200                   
hhea total             2248              2248                   2248                2248                 2248                  
typo total             2248              2248                   2248                2248                 2248                  
win total              2248              2248                   2248                2248                 2248                  
UPM:Heights            2048:1704         2048:1777              2048:1559           2048:1489            2048:1632             
UPM:Heights %          83 %              86 %                   76 %                72 %                 79 %       
$
```

**Comment by MrBrezina** [comment] 2015-01-28 20:39
Yes the fonts are on 2048 UPM, but that is not by error.

The reason why it appears to be smaller is not that it is on 2048 as opposed to 1000. It is the proportion of the ‘main area’ to the rest and we want it that way to avoid clipping in some word-processors and browsers (I seem to remember there was an issue). You can even see that happening in Puralecka Narrow above. We could make the spacing somewhat smaller (that would make the type appear bigger), but that would result in non-standard UPM size (1750 or so).

I do not think rescaling is a good idea at this point. I am afraid it would introduce rounding errors in the actual glyph drawings. In other words, it would not be just changing vertical metrics parameters. Needless to say, it would require us to rebuild everything.

**Comment by davelab6** [comment] 2015-01-28 20:52
Puralecka is clipping and thats a problem with it, but that's that's Omnibus' problem :) 

For example Noto and Ek Mukta are MUCH larger, and work fine, no clipping

**Comment by MrBrezina** [comment] 2015-01-28 21:00
Right, we follow the recommendation that TypoAscender+TypoDescender=UPM. If you want us to break that, we can change the metrics. I think it may result in incosistent line spacing across platforms, but perhaps that is thing of the past?=

**Comment by davelab6** [comment] 2015-01-28 21:16
Fixing up the vertical metrics doesn't effect things:

Here's Ek Mukta on http://www.impallari.com/testing/index-devanagari.php :+1: 

![screen shot 2015-01-28 at 4 15 32 pm](https://cloud.githubusercontent.com/assets/261579/5947121/ecb2d27a-a708-11e4-932b-3ef48baf9132.png)

Here's Eczar untouched:

![screen shot 2015-01-28 at 4 15 34 pm](https://cloud.githubusercontent.com/assets/261579/5947128/f950247e-a708-11e4-86ee-99723bc4ade5.png)

Here's Eczar with the process below:

![screen shot 2015-01-28 at 4 15 39 pm](https://cloud.githubusercontent.com/assets/261579/5947136/015996a0-a709-11e4-9632-bfc8efb189ab.png)

```
$ cd googlefontdirectory/ofl/eczar/ ;
$ fontbakery-fix-vertical-metrics.py Eczar-*.ttf ;
Parameter              Eczar-Bold.ttf    Eczar-Extrabold.ttf    Eczar-Medium.ttf    Eczar-Regular.ttf    Eczar-Semibold.ttf    
ymax                   1110              1143                   1046                1016                 1078                  
hhea.ascent            1288              1288                   1288                1288                 1288                  
OS/2.sTypoAscender     1188              1188                   1188                1188                 1188                  
OS/2.usWinAscent       1288              1288                   1288                1288                 1288                  
ymin                   -594              -634                   -513                -473                 -554                  
hhea.descent           -960              -960                   -960                -960                 -960                  
OS/2.sTypoDescender    -860              -860                   -860                -860                 -860                  
OS/2.usWinDescent      960               960                    960                 960                  960                   
hhea.lineGap           0                 0                      0                   0                    0                     
OS/2.sTypoLineGap      200               200                    200                 200                  200                   
hhea total             2248              2248                   2248                2248                 2248                  
typo total             2248              2248                   2248                2248                 2248                  
win total              2248              2248                   2248                2248                 2248                  
UPM:Heights            2048:1704         2048:1777              2048:1559           2048:1489            2048:1632             
UPM:Heights %          83 %              86 %                   76 %                72 %                 79 %                  

$ fontbakery-fix-vertical-metrics.py --autofix Eczar-*.ttf ; rm *ttf ; rename s/ttf.fix/ttf/g *;
$ fontbakery-fix-vertical-metrics.py Eczar-*.ttf ;
Parameter              Eczar-Bold.ttf    Eczar-Extrabold.ttf    Eczar-Medium.ttf    Eczar-Regular.ttf    Eczar-Semibold.ttf    
ymax                   1110              1143                   1046                1016                 1078                  
hhea.ascent            1143              1143                   1143                1143                 1143                  
OS/2.sTypoAscender     1143              1143                   1143                1143                 1143                  
OS/2.usWinAscent       1143              1143                   1143                1143                 1143                  
ymin                   -594              -634                   -513                -473                 -554                  
hhea.descent           -634              -634                   -634                -634                 -634                  
OS/2.sTypoDescender    -634              -634                   -634                -634                 -634                  
OS/2.usWinDescent      634               634                    634                 634                  634                   
hhea.lineGap           0                 0                      0                   0                    0                     
OS/2.sTypoLineGap      0                 0                      0                   0                    0                     
hhea total             1777              1777                   1777                1777                 1777                  
typo total             1777              1777                   1777                1777                 1777                  
win total              1777              1777                   1777                1777                 1777                  
UPM:Heights            1143:1704         1143:1777              1143:1559           1143:1489            1143:1632             
UPM:Heights %          149 %             155 %                  136 %               130 %                142 %         

$
```

**Comment by davelab6** [comment] 2015-01-28 21:19
@vitalyvolkov looks like there's a bug in fontbakery-fix-vertical-metrics.py - the UPM value in the UPM:Heights line should not change.

**Comment by MrBrezina** [comment] 2015-01-28 23:21
Are saying that: a) there has been some sort of expectations about dimensions from Google that have not been communicated to us, and that b) your tools cannot change the metrics to the way you want them, and c) that we should do that? Is my understanding correct? Because the fonts work perfectly fine as they are. I do not see the reason why they should be scaled like Ek Mukta or Noto, really. Particularly, if this impedes cross-platform operation. While I do not think it would be drastic, I would like to have that clear and confirmed before we spend additional time adapting completely working fonts to your scheme.=

**Comment by davelab6** [comment] 2015-01-29 02:56
> We could make the spacing somewhat smaller (that would make the type
appear bigger), but that would result in non-standard UPM size (1750 or so).

Non-standard UPMs are fine for browsers; for example the
https://github.com/TiroTypeworks/Slabo files have atypical UPM size.
However, I'm not sure that this will make a difference, because - as I
understand things - this is about the relative scaling of the design to the
UPM (whatever it is.)

Are saying that: a) there has been some sort of expectations about
> dimensions from Google that have not been communicated to us,


I don't represent Google, I only speak for myself. When I guessed, "I
believe that the UPM was changed to 2048" I was completely mistaken - sorry
for that.

I think your dimensions look strange in comparison to fonts from other
experienced vendors like Monotype, ITF and Ek; and not just web fonts but
system fonts.

I can understand that for example Dekko is scaled a little smaller than
Hind (in the first image above) because it has taller upper matras; and
that its latin is smaller than it would be in a 'latin only' distribution;
indeed we can see this as Short Stack, from which it has been derived, does
appear larger. But Eczar currently seems about 50% smaller than I expect.

So, maybe the way Eczar is set up is better, and all the other projects
should be rescaled down, or maybe Eczar is set up in a strange way and it
should be scaled up. What do you know that they don't? :)


> and that b) your tools cannot change the metrics to the way you want them,


The tool changes the metrics to the way I want them, which is based on
https://code.google.com/p/googlefontdirectory/wiki/VerticalMetricsRecommendations
- however, I'm curious to better understand why you have set them the way
you have. The y bbox total of Eczar-Extrabold.ttf is 1777, but your
vertical metrics total 2248 for all styles. Why is that?

> > the recommendation that TypoAscender+TypoDescender=UPM

Who made this recommendation, and when? :)


> and c) that we should do that?


I think the vertical metrics is a secondary issue, and I'm happy to submit
a pull request as its just diddilng some numeric metadata values; the
scaling seems like something that you would do rather than me do and submit.


> Is my understanding correct? Because the fonts work perfectly fine as they
> are. I do not see the reason why they should be scaled like Ek Mukta or
> Noto, really.


I don't think users will like to double their CSS font-size values to use
Eczar.


> Particularly, if this impedes cross-platform operation.


I believe that the fonts are intended for use as web fonts primarily. If
its not possible to make fonts that work as expected in web browsers and
for various common desktop systems, perhaps 2 builds will be needed.
However, I'm not aware of anyone else who makes 2 builds for web and
desktop like this.


> While I do not think it would be drastic, I would like to have that clear
> and confirmed before we spend additional time adapting completely working
> fonts to your scheme.


 I agree about wanting more clarity here - I would like to better
understand why Eczar is the way it is :)

**Comment by MrBrezina** [comment] 2015-01-29 11:23
Just to clarify, this effect is no mystery. If we change the UPM, it will be resolved. The question is how much we change it (to 1750 or 1000) The reason for this setup is based purely on the recommendation TypoAscender+TypoDescender=UPM which is included in proofing tools (e.g. in AFDKO). I think it relates to the fact that sometimes the line-height has been calculated from the UPM and sometimes from the TypoAscender+TypoDescender. While this may be dated, I felt that for a font with such exposure, it is good to play it safe.

If you tell me do not worry about that, I will happily change things. I would prefer to do that myself.

**Comment by davelab6** [comment] 2015-01-29 14:00
Ok l review the fdk docs. Was it drawn on a 1000upm and scaled up?

**Comment by MrBrezina** [comment] 2015-01-29 16:28
Yes. But that should not be relevant.

**Comment by davelab6** [comment] 2015-01-29 19:43
how was the scaling from 1000 to 2048 calculated?

**Comment by davelab6** [comment] 2015-01-30 17:19
Okay great! I think the key part of what I wrote above is,

> I believe that the fonts are intended for use as web fonts primarily. If
> its not possible to make fonts that work as expected in web browsers and
> for various common desktop systems, perhaps 2 builds will be needed.

However, its the web version that I'm most interested in :) I would like Eczar to be scaled similarly to the rest, or to better understand why Eczar is the way it is right now.

**Comment by MrBrezina** [comment] 2015-02-03 20:06
It is fixed now. I did not find clipping issues, so I changed to metrics according to the system the other fonts use.

**Closed** 2015-02-03 20:06 UTC

**Comment by davelab6** [comment] 2015-02-03 20:24
Thanks for investigating! I'm curious, which software did you check for
clipping with?

**Comment by MrBrezina** [comment] 2015-02-03 20:35
chrome 28.0 on OS X Mavericks
chrome 28.0 on Windows 7
chrome 28.0 on Windows 8
chrome 28.0 on Windows XP
firefox 25.0 on OS X Mavericks
firefox 25.0 on Windows 7
firefox 25.0 on Windows 8
firefox 25.0 on Windows XP
ie 7.0 on Windows XP
ie 8.0 on Windows 7
ie 9.0 on Windows 7
ie 11.0 on Windows 7
ie 11.0 on Windows 8.1

**Comment by davelab6** [comment] 2015-02-03 20:36
You did it the initial way because of other software. What's the result there?

**Comment by MrBrezina** [comment] 2015-02-03 20:47
I did not test that, because it does not seem relevant to Google, but  I believe you can see clipping happening in most of the word-processors.=
